<?php

namespace Database\Seeders;

use App\Models\AdminActivityLog;
use Illuminate\Database\Seeder;

class AdminActivityLogSeeder extends Seeder
{
    /**
     * Seed the admin_activity_logs table with 25 recent log entries.
     */
    public function run(): void
    {
        $userAgent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36';

        $logs = [
            // Login/Logout
            [
                'type' => 'login',
                'entity' => 'admin',
                'entity_id' => 1,
                'entity_name' => 'Super Admin',
                'description' => 'Accesso admin alla piattaforma',
                'old_values' => null,
                'new_values' => null,
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(7)->setHour(8)->setMinute(30),
            ],
            [
                'type' => 'login',
                'entity' => 'admin',
                'entity_id' => 1,
                'entity_name' => 'Super Admin',
                'description' => 'Accesso admin alla piattaforma',
                'old_values' => null,
                'new_values' => null,
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(6)->setHour(9)->setMinute(15),
            ],
            [
                'type' => 'logout',
                'entity' => 'admin',
                'entity_id' => 1,
                'entity_name' => 'Super Admin',
                'description' => 'Disconnessione admin dalla piattaforma',
                'old_values' => null,
                'new_values' => null,
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(7)->setHour(18)->setMinute(0),
            ],
            // Create operations
            [
                'type' => 'create',
                'entity' => 'category',
                'entity_id' => 1,
                'entity_name' => 'Fotovoltaico',
                'description' => 'Creata nuova categoria: Fotovoltaico',
                'old_values' => null,
                'new_values' => ['name' => 'Fotovoltaico', 'slug' => 'fotovoltaico', 'max_shares' => 3],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(6)->setHour(10)->setMinute(0),
            ],
            [
                'type' => 'create',
                'entity' => 'category',
                'entity_id' => 2,
                'entity_name' => 'Infissi e Serramenti',
                'description' => 'Creata nuova categoria: Infissi e Serramenti',
                'old_values' => null,
                'new_values' => ['name' => 'Infissi e Serramenti', 'slug' => 'infissi-serramenti', 'max_shares' => 3],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(6)->setHour(10)->setMinute(15),
            ],
            [
                'type' => 'create',
                'entity' => 'user',
                'entity_id' => 1,
                'entity_name' => 'SolarTech Italia S.r.l.',
                'description' => 'Registrato nuovo cliente: SolarTech Italia S.r.l.',
                'old_values' => null,
                'new_values' => ['email' => 'info@solartech-italia.it', 'status' => 'active'],
                'ip_address' => '10.0.0.1',
                'created_at' => now()->subDays(5)->setHour(11)->setMinute(30),
            ],
            [
                'type' => 'create',
                'entity' => 'user',
                'entity_id' => 2,
                'entity_name' => 'EdilGreen S.p.A.',
                'description' => 'Registrato nuovo cliente: EdilGreen S.p.A.',
                'old_values' => null,
                'new_values' => ['email' => 'commerciale@edilgreen.it', 'status' => 'active'],
                'ip_address' => '10.0.0.1',
                'created_at' => now()->subDays(5)->setHour(14)->setMinute(0),
            ],
            [
                'type' => 'create',
                'entity' => 'package',
                'entity_id' => 1,
                'entity_name' => 'Starter Fotovoltaico',
                'description' => 'Creato nuovo pacchetto: Starter Fotovoltaico',
                'old_values' => null,
                'new_values' => ['name' => 'Starter Fotovoltaico', 'exclusive_price' => 150.00],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(5)->setHour(15)->setMinute(0),
            ],
            // Update operations
            [
                'type' => 'update',
                'entity' => 'pricing',
                'entity_id' => 1,
                'entity_name' => 'Fotovoltaico - Prezzi',
                'description' => 'Aggiornati prezzi per categoria Fotovoltaico',
                'old_values' => ['exclusive_price' => 29.75],
                'new_values' => ['exclusive_price' => 35.00],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(4)->setHour(9)->setMinute(0),
            ],
            [
                'type' => 'update',
                'entity' => 'lead',
                'entity_id' => 1,
                'entity_name' => 'Lead #1',
                'description' => 'Aggiornato stato lead da free a sold_exclusive',
                'old_values' => ['status' => 'free'],
                'new_values' => ['status' => 'sold_exclusive'],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(4)->setHour(10)->setMinute(30),
            ],
            [
                'type' => 'update',
                'entity' => 'client',
                'entity_id' => 3,
                'entity_name' => 'Clima Service S.r.l.',
                'description' => 'Aggiornato profilo cliente: Clima Service S.r.l.',
                'old_values' => ['phone' => '+39 055 0000000'],
                'new_values' => ['phone' => '+39 055 4567890'],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(4)->setHour(14)->setMinute(45),
            ],
            // Status change
            [
                'type' => 'status_change',
                'entity' => 'user',
                'entity_id' => 10,
                'entity_name' => 'Caldaie Piemonte S.n.c.',
                'description' => 'Stato utente cambiato da active a suspended',
                'old_values' => ['status' => 'active'],
                'new_values' => ['status' => 'suspended'],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(3)->setHour(11)->setMinute(0),
            ],
            [
                'type' => 'status_change',
                'entity' => 'order',
                'entity_id' => 1,
                'entity_name' => 'ORD-2026-00001',
                'description' => 'Stato ordine cambiato da pending a paid',
                'old_values' => ['status' => 'pending'],
                'new_values' => ['status' => 'paid'],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(3)->setHour(14)->setMinute(30),
            ],
            [
                'type' => 'status_change',
                'entity' => 'order',
                'entity_id' => 11,
                'entity_name' => 'ORD-2026-00011',
                'description' => 'Stato ordine cambiato da paid a completed',
                'old_values' => ['status' => 'paid'],
                'new_values' => ['status' => 'completed'],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(3)->setHour(16)->setMinute(0),
            ],
            // Config change
            [
                'type' => 'config_change',
                'entity' => 'system',
                'entity_id' => null,
                'entity_name' => 'default_free_trial_leads',
                'description' => 'Aggiornata impostazione: default_free_trial_leads da 3 a 5',
                'old_values' => ['default_free_trial_leads' => 3],
                'new_values' => ['default_free_trial_leads' => 5],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(2)->setHour(9)->setMinute(0),
            ],
            [
                'type' => 'config_change',
                'entity' => 'system',
                'entity_id' => null,
                'entity_name' => 'smtp_host',
                'description' => 'Aggiornata configurazione SMTP',
                'old_values' => ['smtp_host' => 'old.smtp.example.com'],
                'new_values' => ['smtp_host' => 'smtp.example.com'],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(2)->setHour(10)->setMinute(30),
            ],
            // Export
            [
                'type' => 'export',
                'entity' => 'lead',
                'entity_id' => null,
                'entity_name' => 'Export Lead',
                'description' => 'Esportazione lead in formato CSV: 80 record',
                'old_values' => null,
                'new_values' => ['format' => 'csv', 'records' => 80],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(2)->setHour(15)->setMinute(0),
            ],
            [
                'type' => 'export',
                'entity' => 'order',
                'entity_id' => null,
                'entity_name' => 'Export Ordini',
                'description' => 'Esportazione ordini in formato CSV: 20 record',
                'old_values' => null,
                'new_values' => ['format' => 'csv', 'records' => 20],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(2)->setHour(15)->setMinute(30),
            ],
            [
                'type' => 'export',
                'entity' => 'invoice',
                'entity_id' => null,
                'entity_name' => 'Export Fatture',
                'description' => 'Esportazione fatture in formato PDF',
                'old_values' => null,
                'new_values' => ['format' => 'pdf', 'records' => 13],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(1)->setHour(9)->setMinute(0),
            ],
            // Delete
            [
                'type' => 'delete',
                'entity' => 'category',
                'entity_id' => 8,
                'entity_name' => 'Isolamento Termico',
                'description' => 'Categoria disattivata: Isolamento Termico (soft delete)',
                'old_values' => ['is_active' => true],
                'new_values' => ['is_active' => false],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(1)->setHour(10)->setMinute(0),
            ],
            // More recent login/activity
            [
                'type' => 'login',
                'entity' => 'admin',
                'entity_id' => 1,
                'entity_name' => 'Super Admin',
                'description' => 'Accesso admin alla piattaforma',
                'old_values' => null,
                'new_values' => null,
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(1)->setHour(8)->setMinute(45),
            ],
            [
                'type' => 'update',
                'entity' => 'lead',
                'entity_id' => 21,
                'entity_name' => 'Lead #21',
                'description' => 'Aggiornato stato lead da free a sold_exclusive',
                'old_values' => ['status' => 'free'],
                'new_values' => ['status' => 'sold_exclusive'],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(1)->setHour(11)->setMinute(15),
            ],
            [
                'type' => 'create',
                'entity' => 'lead',
                'entity_id' => 75,
                'entity_name' => 'Lead #75',
                'description' => 'Inserito manualmente nuovo lead per categoria Ristrutturazioni',
                'old_values' => null,
                'new_values' => ['category_id' => 6, 'source_id' => 5, 'status' => 'free'],
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subDays(1)->setHour(14)->setMinute(0),
            ],
            // Password reset
            [
                'type' => 'password_reset',
                'entity' => 'user',
                'entity_id' => 8,
                'entity_name' => 'GreenBuild Sicilia S.r.l.',
                'description' => 'Reset password eseguito per utente GreenBuild Sicilia S.r.l.',
                'old_values' => null,
                'new_values' => null,
                'ip_address' => '192.168.1.100',
                'created_at' => now()->subHours(6),
            ],
            [
                'type' => 'login',
                'entity' => 'admin',
                'entity_id' => 1,
                'entity_name' => 'Super Admin',
                'description' => 'Accesso admin alla piattaforma',
                'old_values' => null,
                'new_values' => null,
                'ip_address' => '192.168.1.101',
                'created_at' => now()->subHours(2),
            ],
        ];

        foreach ($logs as $log) {
            AdminActivityLog::create(array_merge([
                'admin_id' => 1,
                'admin_name' => 'Super Admin',
                'admin_email' => 'admin@qualeadfied.com',
                'user_agent' => $userAgent,
            ], $log));
        }
    }
}
