<?php

namespace Database\Seeders;

use App\Models\ClientProfile;
use App\Models\User;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Seed the users table with 10 B2B users and their client profiles.
     */
    public function run(): void
    {
        $users = [
            [
                'email' => 'info@solartech-italia.it',
                'password' => 'password',
                'role' => 'client',
                'status' => 'active',
                'email_verified_at' => now(),
                'profile' => [
                    'company_name' => 'SolarTech Italia S.r.l.',
                    'vat_number' => 'IT01234567890',
                    'phone' => '+39 02 1234567',
                    'first_name' => 'Marco',
                    'last_name' => 'Rossi',
                    'billing_address' => 'Via Roma 42',
                    'billing_city' => 'Milano',
                    'billing_province' => 'MI',
                    'billing_zip' => '20121',
                    'billing_country' => 'IT',
                    'sdi_code' => 'M5UXCR1',
                    'pec_email' => 'solartech@pec.it',
                    'free_trial_enabled' => false,
                    'free_trial_leads_remaining' => 0,
                    'email_notifications_enabled' => true,
                    'marketing_consent' => true,
                ],
            ],
            [
                'email' => 'commerciale@edilgreen.it',
                'password' => 'password',
                'role' => 'client',
                'status' => 'active',
                'email_verified_at' => now(),
                'profile' => [
                    'company_name' => 'EdilGreen S.p.A.',
                    'vat_number' => 'IT02345678901',
                    'phone' => '+39 06 9876543',
                    'first_name' => 'Luca',
                    'last_name' => 'Bianchi',
                    'billing_address' => 'Viale Europa 15',
                    'billing_city' => 'Roma',
                    'billing_province' => 'RM',
                    'billing_zip' => '00144',
                    'billing_country' => 'IT',
                    'sdi_code' => 'KRRH6B9',
                    'pec_email' => 'edilgreen@pec.it',
                    'free_trial_enabled' => true,
                    'free_trial_leads_remaining' => 5,
                    'email_notifications_enabled' => true,
                    'marketing_consent' => true,
                ],
            ],
            [
                'email' => 'acquisti@climaservice.it',
                'password' => 'password',
                'role' => 'client',
                'status' => 'active',
                'email_verified_at' => now(),
                'profile' => [
                    'company_name' => 'Clima Service S.r.l.',
                    'vat_number' => 'IT03456789012',
                    'phone' => '+39 055 4567890',
                    'first_name' => 'Giuseppe',
                    'last_name' => 'Verdi',
                    'billing_address' => 'Via dei Mille 8',
                    'billing_city' => 'Firenze',
                    'billing_province' => 'FI',
                    'billing_zip' => '50121',
                    'billing_country' => 'IT',
                    'sdi_code' => 'W7YVJK9',
                    'pec_email' => 'climaservice@pec.it',
                    'free_trial_enabled' => false,
                    'free_trial_leads_remaining' => 0,
                    'email_notifications_enabled' => true,
                    'marketing_consent' => false,
                ],
            ],
            [
                'email' => 'info@termoidraulica-napoli.it',
                'password' => 'password',
                'role' => 'client',
                'status' => 'active',
                'email_verified_at' => now(),
                'profile' => [
                    'company_name' => 'Termoidraulica Napoli S.r.l.',
                    'vat_number' => 'IT04567890123',
                    'phone' => '+39 081 7654321',
                    'first_name' => 'Antonio',
                    'last_name' => 'Esposito',
                    'billing_address' => 'Corso Umberto I 120',
                    'billing_city' => 'Napoli',
                    'billing_province' => 'NA',
                    'billing_zip' => '80138',
                    'billing_country' => 'IT',
                    'sdi_code' => 'J6URRTW',
                    'pec_email' => 'termoidraulica.napoli@pec.it',
                    'free_trial_enabled' => true,
                    'free_trial_leads_remaining' => 3,
                    'email_notifications_enabled' => true,
                    'marketing_consent' => true,
                ],
            ],
            [
                'email' => 'direzione@infissipro.it',
                'password' => 'password',
                'role' => 'client',
                'status' => 'active',
                'email_verified_at' => now(),
                'profile' => [
                    'company_name' => 'InfissiPro S.r.l.',
                    'vat_number' => 'IT05678901234',
                    'phone' => '+39 011 2345678',
                    'first_name' => 'Paolo',
                    'last_name' => 'Ferrari',
                    'billing_address' => 'Corso Francia 210',
                    'billing_city' => 'Torino',
                    'billing_province' => 'TO',
                    'billing_zip' => '10138',
                    'billing_country' => 'IT',
                    'sdi_code' => 'SUBM70N',
                    'pec_email' => 'infissipro@pec.it',
                    'free_trial_enabled' => false,
                    'free_trial_leads_remaining' => 0,
                    'email_notifications_enabled' => true,
                    'marketing_consent' => true,
                ],
            ],
            [
                'email' => 'vendite@energyhouse.it',
                'password' => 'password',
                'role' => 'client',
                'status' => 'active',
                'email_verified_at' => now(),
                'profile' => [
                    'company_name' => 'Energy House S.r.l.',
                    'vat_number' => 'IT06789012345',
                    'phone' => '+39 045 8901234',
                    'first_name' => 'Francesca',
                    'last_name' => 'Colombo',
                    'billing_address' => 'Via Verdi 55',
                    'billing_city' => 'Verona',
                    'billing_province' => 'VR',
                    'billing_zip' => '37121',
                    'billing_country' => 'IT',
                    'sdi_code' => 'A4707H7',
                    'pec_email' => 'energyhouse@pec.it',
                    'free_trial_enabled' => false,
                    'free_trial_leads_remaining' => 0,
                    'email_notifications_enabled' => false,
                    'marketing_consent' => true,
                ],
            ],
            [
                'email' => 'admin@ristruttura-facile.it',
                'password' => 'password',
                'role' => 'client',
                'status' => 'active',
                'email_verified_at' => now(),
                'profile' => [
                    'company_name' => 'Ristruttura Facile S.a.s.',
                    'vat_number' => 'IT07890123456',
                    'phone' => '+39 051 3456789',
                    'first_name' => 'Alessandro',
                    'last_name' => 'Moretti',
                    'billing_address' => 'Via Indipendenza 33',
                    'billing_city' => 'Bologna',
                    'billing_province' => 'BO',
                    'billing_zip' => '40121',
                    'billing_country' => 'IT',
                    'sdi_code' => 'T9K4ZHO',
                    'pec_email' => 'ristrutturafacile@pec.it',
                    'free_trial_enabled' => false,
                    'free_trial_leads_remaining' => 0,
                    'email_notifications_enabled' => true,
                    'marketing_consent' => false,
                ],
            ],
            [
                'email' => 'info@greenbuild-sicilia.it',
                'password' => 'password',
                'role' => 'client',
                'status' => 'pending',
                'email_verified_at' => null,
                'profile' => [
                    'company_name' => 'GreenBuild Sicilia S.r.l.',
                    'vat_number' => 'IT08901234567',
                    'phone' => '+39 091 6543210',
                    'first_name' => 'Salvatore',
                    'last_name' => 'Ferrara',
                    'billing_address' => 'Via Maqueda 200',
                    'billing_city' => 'Palermo',
                    'billing_province' => 'PA',
                    'billing_zip' => '90133',
                    'billing_country' => 'IT',
                    'sdi_code' => 'N8PQ3R2',
                    'pec_email' => 'greenbuild.sicilia@pec.it',
                    'free_trial_enabled' => true,
                    'free_trial_leads_remaining' => 5,
                    'email_notifications_enabled' => true,
                    'marketing_consent' => true,
                ],
            ],
            [
                'email' => 'contatto@isoltherm.it',
                'password' => 'password',
                'role' => 'client',
                'status' => 'pending',
                'email_verified_at' => null,
                'profile' => [
                    'company_name' => 'IsolTherm S.r.l.',
                    'vat_number' => 'IT09012345678',
                    'phone' => '+39 010 7890123',
                    'first_name' => 'Roberto',
                    'last_name' => 'Conti',
                    'billing_address' => 'Via XX Settembre 45',
                    'billing_city' => 'Genova',
                    'billing_province' => 'GE',
                    'billing_zip' => '16121',
                    'billing_country' => 'IT',
                    'sdi_code' => 'L5MX2K8',
                    'pec_email' => 'isoltherm@pec.it',
                    'free_trial_enabled' => false,
                    'free_trial_leads_remaining' => 0,
                    'email_notifications_enabled' => true,
                    'marketing_consent' => false,
                ],
            ],
            [
                'email' => 'vendite@caldaiepiemonte.it',
                'password' => 'password',
                'role' => 'client',
                'status' => 'suspended',
                'email_verified_at' => now()->subMonths(3),
                'profile' => [
                    'company_name' => 'Caldaie Piemonte S.n.c.',
                    'vat_number' => 'IT10123456789',
                    'phone' => '+39 011 8765432',
                    'first_name' => 'Giovanni',
                    'last_name' => 'Ricci',
                    'billing_address' => 'Via Po 78',
                    'billing_city' => 'Torino',
                    'billing_province' => 'TO',
                    'billing_zip' => '10124',
                    'billing_country' => 'IT',
                    'sdi_code' => 'B7VN4P1',
                    'pec_email' => 'caldaiepiemonte@pec.it',
                    'free_trial_enabled' => false,
                    'free_trial_leads_remaining' => 0,
                    'email_notifications_enabled' => false,
                    'marketing_consent' => false,
                ],
            ],
        ];

        foreach ($users as $userData) {
            $profileData = $userData['profile'];
            unset($userData['profile']);

            $user = User::create($userData);
            $profileData['user_id'] = $user->id;
            ClientProfile::create($profileData);
        }
    }
}
